### ISSUE TITLE
Переведите код под UDL 

### ISSUE THREAD

**Issue by evshvarov** [MyasnikovIA/ZSrvController#1]

**Comment by MyasnikovIA** [comment]
Пожелание выполнено: %ZMSrv.Controller_V1.cls

**Comment by evshvarov** [comment]
О, спасибо!
А можно еще топик cacheobjectscript-udl добавить тогда?
репо появится здесь: https://github.com/topics/cacheobjectscript-udl

**Comment by MyasnikovIA** [comment]
Добрый день.
Честно говоря я не совсем понял, что надо добавить. И в связи с этим не знаю что сделать :) .  Если вы поясните, о чем идет речь, то я добавлю. 
С GitHub недавно работаю в терминах еще плаваю...

**Comment by MyasnikovIA** [comment]
Нашел. Добавил... :)

**Comment by evshvarov** [comment]
О, отлично! [50 репозиториев](https://github.com/topics/cacheobjectscript-udl) уже.
Как наберется 100, гитхаб добавит подсветку COS в UDL.
