### ISSUE TITLE
Сделайте класс непроцентным

### ISSUE THREAD

**Issue by evshvarov** [MyasnikovIA/ZSrvController#2]
А маппировать можно в %ALL чтобы он был библиотечным.
Вот я статью по этому поводу написал еще: https://community.intersystems.com/post/distributing-library-packages-percent-classes-vs-all-namespace

**Comment by MyasnikovIA** [comment]
Добрый день. 
1) Из прочитанной статьи я так и не понял, как стоит назвать класс. К сожалению не хватает маленького примера. 
2) Потом если класс назвать %Z###.### тогда для развертывания нет необходимости переключать CACHELIB  в режим записи.

Подскажите как стоит назвать класс , и я это сделаю

**Comment by evshvarov** [comment]
Ну если он %Z, то вроде и ОК. закрывается вопрос )
